import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  EN: {
    // Nav
    nav_features: 'Platform Engines',
    nav_console: 'Management Console',
    nav_roi: 'ROI Estimator',
    nav_pricing: 'Enterprise Pricing',
    nav_demo_btn: 'Console Demo',
    nav_trial_btn: 'Start 14-Day Trial',

    // Hero
    hero_badge: 'NEXT-GEN FASHION E-COMMERCE OPERATING SYSTEM',
    hero_title: 'Empowering Fashion Brands With Next-Gen Operating System',
    hero_sub: 'Shopdy is the unified B2B platform engineered specifically for fashion houses and apparel D2C brands. Manage multi-storefronts, AI Size Matcher, 3D Lookbook Builder, Omnichannel POS, and 500,000 req/min Flash Sale surges from a single powerful management dashboard.',
    hero_cta_trial: 'Launch 14-Day Free Platform Trial',
    hero_cta_demo: 'Explore Interactive Console Demo',
    hero_check1: '14-Day Full Access Trial',
    hero_check2: 'TikTok & Instagram POS Sync',
    hero_check3: '5-Minute Store Setup',
    hero_core_title: 'Shopdy Fashion OS • Control Center',
    hero_core_status: 'Live Engine',
    hero_core_trust: '1,200+ Fashion Brands Onboarded',
    hero_core_saas: 'SaaS Enterprise',

    // Metrics
    metric_uptime: 'Uptime Flash Sale SLA',
    metric_return: 'Lower Return Rate (AI Size)',
    metric_conversion: 'Conversion Rate Uplift',
    metric_surge: 'Traffic Surge Req / Min',

    // Brand Scroller
    brand_trusted: 'Trusted by over 1,200+ Premier Fashion Brands & Haute Couture Houses Worldwide',

    // Velocity Marquee
    marquee_items: [
      'HAUTE COUTURE OS',
      'AI SIZE MATCHER',
      '3D LOOKBOOK STUDIO',
      'OMNICHANNEL POS SYNC',
      'FLASH SALE MATRIX 500K RPM',
      '99.99% UPTIME SLA',
    ],

    // Core Features
    features_badge: 'ENGINEERED EXCLUSIVELY FOR FASHION ENTERPRISES',
    features_title: 'State-of-the-Art Platform Engines Driving',
    features_title_highlight: '3.2x Revenue Growth',
    features_sub: 'Shopdy resolves core fashion e-commerce pain points: sizing return costs, flash drop server crashes, and complex SKU matrix synchronization.',
    features_explore: 'Explore Architecture Specification →',
    
    // Feature Cards
    feat_1_title: 'AI Size & Fit Matcher',
    feat_1_tag: 'Built-in AI Fitting Engine',
    feat_1_desc: 'Delivers 98.4% fit accuracy based on body parameters and brand-specific garment measurements, cutting return rates by 45%.',

    feat_2_title: 'Visual Lookbook 3D & 4K Studio',
    feat_2_tag: 'Haute Couture Visuals',
    feat_2_desc: 'Immersive storefront builder with 4K video banners, 360° interactive 3D outfit pairing, and drag-and-drop editorial layouts.',

    feat_3_title: 'Omnichannel & Live POS Sync',
    feat_3_tag: 'Realtime Multi-Channel',
    feat_3_desc: 'Real-time two-way synchronization of stock and orders across TikTok Shop, Instagram Shopping, Facebook Live, and physical boutique POS.',

    feat_4_title: 'Flash Sale Matrix (500k RPM)',
    feat_4_tag: 'Zero Downtime Guarantee',
    feat_4_desc: 'Serverless Cloud Native infrastructure auto-scales up to 500,000 requests/min to handle hype limited edition drops seamlessly.',

    feat_5_title: 'Multi-SKU Variant Matrix',
    feat_5_tag: 'Pre-Order & Variant Control',
    feat_5_desc: 'Effortlessly manage millions of product variants (size, color, material, seasonal drops). Supports automated pre-order deposit workflows.',

    feat_6_title: 'Luxury Fulfillment & QR Auth',
    feat_6_tag: 'Anti-Counterfeit Protection',
    feat_6_desc: 'Generates encrypted QR tags on physical garments for authenticity verification, integrated 2H express delivery routing and luxury packaging.',

    // Console Demo
    demo_badge: 'LIVE INTERACTIVE CONSOLE DEMO',
    demo_title: 'Experience the',
    demo_title_highlight: 'Shopdy Platform Console',
    demo_sub: 'Switch between management modules below to explore how Shopdy streamlines fashion operations and storefront design.',
    tab_1: '1. Storefront Visual Studio',
    tab_2: '2. Operations & Analytics Console',
    tab_3: '3. AI Outfit Pairing Controller',
    demo_modal_btn: 'Launch Simulated Storefront Modal',
    demo_view_lookbook: 'View Storefront',

    // ROI Calculator
    roi_badge: 'FINANCIAL PERFORMANCE CALCULATOR',
    roi_title: 'Calculate Projected Revenue & Savings With',
    roi_sub: 'Drag the interactive sliders below to estimate the annual operational savings from reduced returns and the additional revenue generated by migrating to Shopdy.',
    roi_orders_label: 'Monthly Order Volume:',
    roi_aov_label: 'Average Order Value (AOV):',
    roi_total_label: 'Estimated Additional Revenue & Saved Operational Costs / Year:',
    roi_return_saved: 'Saved Sizing Return Shipping Costs:',
    roi_extra_rev: 'Added Revenue From Storefront UX:',
    roi_cta: 'Start Optimizing Brand Profits With Shopdy',

    // Testimonials
    test_badge: 'REAL FASHION BRAND SUCCESS STORIES',
    test_title: 'Fashion Houses Accelerating With',
    test_lookbook_title: '✦ Featured Lookbook Storefronts Powered By Shopdy',

    // Pricing
    pricing_badge: 'TRANSPARENT ENTERPRISE PRICING — NO HIDDEN FEES',
    pricing_title: 'Invest in Scalable',
    pricing_title_highlight: 'Brand Growth',
    pricing_sub: 'All plans include a 14-day free trial with full access to platform management tools.',
    pricing_monthly: 'Billed Monthly',
    pricing_annual: 'Billed Annually',
    pricing_save_badge: 'Save 20%',
    pricing_popular: '✦ Most Popular Choice',

    // CTA Banner
    cta_badge: 'READY TO ELEVATE YOUR FASHION ENTERPRISE?',
    cta_title: 'Launch Your Custom Platform Subdomain in',
    cta_title_highlight: '60 Seconds',
    cta_sub: 'Experience the complete power of Shopdy OS: AI Size Matcher, 3D Lookbook Studio, and Flash Sale Infrastructure. Instant 14-day free trial activation.',
    cta_btn: 'Launch Demo Storefront',

    // Footer
    footer_desc: 'Shopdy is the Next-Gen B2B Fashion E-Commerce Operating System and Management Platform tailored for Haute Couture Luxury Houses, D2C Brands, and Retail Chains.',
    footer_status: 'Shopdy Engine 3.0: 99.99% Operational SLA',
    footer_col_1: 'Platform Engines',
    footer_col_2: 'Brand Resources',
    footer_col_3: 'Global Offices',
  },

  VI: {
    // Nav
    nav_features: 'Bộ Công Cụ OS',
    nav_console: 'Bảng Điều Khiển Live',
    nav_roi: 'Tính Lợi Nhuận ROI',
    nav_pricing: 'Bảng Giá Enterprise',
    nav_demo_btn: 'Xem Live Console',
    nav_trial_btn: 'Dùng Thử 14 Ngày',

    // Hero
    hero_badge: 'HỆ ĐIỀU HÀNH THƯƠNG MẠI ĐIỆN TỬ THỜI TRANG THẾ HỆ MỚI',
    hero_title: 'Nền Tảng Điều Hành Đẳng Cấp Cho Brand Thời Trang',
    hero_sub: 'Shopdy là nền tảng B2B quản trị toàn diện thiết kế riêng cho các thương hiệu thời trang & luxury house. Quản lý đa cửa hàng, AI gợi ý size chuẩn 98%, Visual Lookbook 3D, Omnichannel POS và hạ tầng Flash Sale chịu tải 500,000 traffic/phút trên một bảng điều khiển duy nhất.',
    hero_cta_trial: 'Khởi Tạo Platform Dùng Thử 14 Ngày',
    hero_cta_demo: 'Khám Phá Bảng Quản Trị Live Console',
    hero_check1: 'Dùng thử 14 ngày không cần thẻ',
    hero_check2: 'Đồng bộ TikTok & Instagram POS',
    hero_check3: 'Setup hệ thống trong 5 phút',
    hero_core_title: 'Shopdy Fashion OS • Trung Tâm Quản Trị',
    hero_core_status: 'Hạ Tầng Hoạt Động',
    hero_core_trust: 'Hơn 1,200+ Brand Đang Sử Dụng',
    hero_core_saas: 'SaaS Enterprise',

    // Metrics
    metric_uptime: 'Cam Kết Uptime Flash Sale SLA',
    metric_return: 'Giảm Tỉ Lệ Đổi Trả (Nhờ AI Size)',
    metric_conversion: 'Tăng Tỉ Lệ Chuyển Đổi',
    metric_surge: 'Kháng Tải Traffic Req / Phút',

    // Brand Scroller
    brand_trusted: 'Được tin dùng bởi hơn 1,200+ Thương hiệu thời trang & Nhà mốt hàng đầu',

    // Velocity Marquee
    marquee_items: [
      'HAUTE COUTURE OS',
      'AI SIZE MATCHER',
      '3D LOOKBOOK STUDIO',
      'OMNICHANNEL POS SYNC',
      'FLASH SALE MATRIX 500K RPM',
      '99.99% UPTIME SLA',
    ],

    // Core Features
    features_badge: 'THIẾT KẾ CHUYÊN BIỆT CHO DOANH NGHIỆP THỜI TRANG',
    features_title: 'Công Nghệ Nền Tảng Đột Phá Giúp Tăng',
    features_title_highlight: '3.2x Doanh Thu',
    features_sub: 'Shopdy giải quyết triệt để những nỗi đau riêng của ngành thời trang: Trả hàng sai size, giật lag khi mở bán BST hot, và quản lý biến thể SKU phức tạp.',
    features_explore: 'Tìm hiểu thông số kiến trúc &rarr;',

    // Feature Cards
    feat_1_title: 'AI Size & Fit Matcher',
    feat_1_tag: 'Thuật Toán Gợi Ý Size AI',
    feat_1_desc: 'Đạt độ chính xác 98.4% dựa trên số đo cơ thể và thông số form dáng riêng của brand, giúp giảm ngay 45% phí ship đổi trả hàng.',

    feat_2_title: 'Visual Lookbook 3D & 4K Studio',
    feat_2_tag: 'Giao Diện Haute Couture',
    feat_2_desc: 'Trình thiết kế giao diện kéo thả chuẩn cao cấp với banner video 4K mượt mà, Lookbook tương tác 360° và phối đồ Mix & Match trực quan.',

    feat_3_title: 'Omnichannel & Live POS Sync',
    feat_3_tag: 'Đồng Bộ Đa Kênh Realtime',
    feat_3_desc: 'Đồng bộ hai chiều tức thì tồn kho và đơn hàng giữa TikTok Shop, Instagram Shopping, Facebook Live và hệ thống Showroom POS offline.',

    feat_4_title: 'Flash Sale Matrix (500k RPM)',
    feat_4_tag: 'Cam Kết Không Sập Web',
    feat_4_desc: 'Hạ tầng Cloud Native tự động mở rộng chịu tải tới 500,000 lượt truy cập/phút cho các đợt mở bán bộ sưu tập Limited Edition hot nhất.',

    feat_5_title: 'Multi-SKU Variant Matrix',
    feat_5_tag: 'Quản Lý Biến Thể & Pre-Order',
    feat_5_desc: 'Quản lý mượt mà hàng triệu biến thể (Size, Màu sắc, Chất liệu, BST theo mùa). Hỗ trợ quy trình nhận cọc đặt hàng Pre-order tự động.',

    feat_6_title: 'Luxury Fulfillment & QR Auth',
    feat_6_tag: 'Bảo Vệ Chống Hàng Giả',
    feat_6_desc: 'Tự động tạo mã QR chống hàng giả mã hóa trên tem tag sản phẩm, tích hợp điều hướng giao hàng hỏa tốc 2H và quy trình đóng hộp Luxury.',

    // Console Demo
    demo_badge: 'DEMO TƯƠNG TÁC BẢNG QUẢN TRỊ',
    demo_title: 'Trải Nghiệm Trực Tiếp',
    demo_title_highlight: 'Hệ Thống Shopdy OS',
    demo_sub: 'Chuyển đổi giữa các phân hệ quản lý bên dưới để khám phá lý do tại sao Shopdy tối ưu vượt trội cho vận hành thương hiệu thời trang.',
    tab_1: '1. Storefront Visual Studio',
    tab_2: '2. Operations & Analytics Console',
    tab_3: '3. AI Outfit Pairing Controller',
    demo_modal_btn: 'Mở Modal Trải Nghiệm Live Storefront',
    demo_view_lookbook: 'Xem Storefront',

    // ROI Calculator
    roi_badge: 'CÔNG CỤ TÍNH TOÁN HIỆU QUẢ TÀI CHÍNH',
    roi_title: 'Tính Toán Doanh Thu & Tiết Kiệm Chi Phí Với',
    roi_sub: 'Kéo thanh trượt bên dưới để ước tính lượng chi phí vận hành đổi trả hàng sẽ tiết kiệm được và doanh thu tăng trưởng khi chuyển sang Shopdy.',
    roi_orders_label: 'Số lượng đơn hàng / tháng:',
    roi_aov_label: 'Giá trị đơn hàng trung bình (AOV):',
    roi_total_label: 'Tổng Chi Phí Tiết Kiệm & Doanh Thu Tăng Thêm / Năm:',
    roi_return_saved: 'Tiết kiệm phí ship đổi trả (Nhờ AI Size):',
    roi_extra_rev: 'Doanh thu tăng thêm từ tối ưu trải nghiệm UX:',
    roi_cta: 'Bắt Đầu Tối Ưu Lợi Nhuận Với Shopdy Ngay',

    // Testimonials
    test_badge: 'CÂU CHUYỆN THÀNH CÔNG THỰC TẾ',
    test_title: 'Các Brand Thời Trang Bứt Phá Cùng',
    test_lookbook_title: '✦ Bộ Sưu Tập Lookbook Storefront Tiêu Biểu Bằng Shopdy',

    // Pricing
    pricing_badge: 'BẢNG GIÁ ENTERPRISE MINH BẠCH — KHÔNG PHÍ ẨN',
    pricing_title: 'Đầu Tư Cho Sự',
    pricing_title_highlight: 'Tăng Trưởng Bền Vững',
    pricing_sub: 'Tất cả gói cước đều bao gồm 14 ngày dùng thử miễn phí đầy đủ tính năng quản trị nền tảng.',
    pricing_monthly: 'Thanh Toán Theo Tháng',
    pricing_annual: 'Thanh Toán Theo Năm',
    pricing_save_badge: 'Tiết kiệm 20%',
    pricing_popular: '✦ Gói Được Chọn Nhiều Nhất',

    // CTA Banner
    cta_badge: 'SẴN SÀNG NÂNG TẦM THƯƠNG HIỆU THỜI TRANG?',
    cta_title: 'Khởi Tạo Tên Miền Độc Quyền Của Brand Trong',
    cta_title_highlight: '60 Giây',
    cta_sub: 'Trải nghiệm toàn bộ sức mạnh của Shopdy OS: AI Size Matcher, 3D Lookbook Studio và Hạ tầng Flash Sale. Dùng thử miễn phí 14 ngày tức thì.',
    cta_btn: 'Khởi Tạo Store Demo',

    // Footer
    footer_desc: 'Shopdy là Hệ điều hành & Nền tảng E-Commerce B2B chuyên biệt thế hệ mới dành cho các Thương hiệu thời trang, Haute Couture Luxury House & Retail Chain.',
    footer_status: 'Hệ thống Shopdy Engine 3.0: 99.99% Operational SLA',
    footer_col_1: 'Bộ Công Cụ Platform',
    footer_col_2: 'Tài Nguyên Brand',
    footer_col_3: 'Văn Phòng Toàn Cầu',
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('EN');

  const toggleLanguage = () => {
    setLang((prev) => (prev === 'EN' ? 'VI' : 'EN'));
  };

  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
